Fix script tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        machine: [ windows-2022, ubuntu-20.04, macos-11 ]
+        include:
+          - machine: windows-2022
+            log-dir: "/c/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs"
+          - machine: ubuntu-20.04
+            log-dir: "/var/log/opentelemetry/dotnet"
+          - machine: macos-11
+            log-dir: "/var/log/opentelemetry/dotnet"
     runs-on: ${{ matrix.machine }}
     steps:
       - uses: actions/checkout@v3.1.0
@@ -22,6 +28,33 @@ jobs:
             6.0.403
             7.0.100
       - run: ./build.cmd Workflow
+      - run: brew install coreutils
+        if: ${{ runner.os == 'macOS' }}
+      - name: Test the Shell scripts from README.md
+        shell: bash
+        run: |
+          set -e
+          export OTEL_DOTNET_AUTO_HOME="${PWD}/OpenTelemetryDistribution"
+          . ./instrument.sh
+          echo $OTEL_DOTNET_AUTO_HOME
+          dotnet help
+          test "$(ls -A '${{ matrix.log-dir }}' )"
+      - name: Test the PowerShell module instructions from README.md
+        if: ${{ runner.os == 'Windows' }}
+        shell: powershell
+        run: |
+          $log_path = "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\*"
+          Import-Module Splunk.OTel.DotNet.psm1
+          [System.Environment]::SetEnvironmentVariable("SPLUNK_OTEL_DOTNET_AUTO_INSTALL_DIR", "${PWD}\OpenTelemetryDistribution", [System.EnvironmentVariableTarget]::Machine)
+          Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
+          dotnet help
+          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
+          if (-not (Test-Path $log_path)) { throw "Log file does not exist. Instrumentation test failed." }
+          Remove-Item $log_path
+          Unregister-OpenTelemetryForCurrentSession
+          dotnet help
+          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
+          if (Test-Path $log_path) { throw "Log file exists. Instrumentation unregister failed." }
       - uses: actions/upload-artifact@v3.1.1
         with:
           name: bin-${{ matrix.machine }}
@@ -52,64 +85,3 @@ jobs:
       with:
         name: bin-${{ matrix.base-image }}
         path: bin/splunk-*.zip
-
-  powershell-script:
-    runs-on: windows-2022
-    steps:
-      - uses: actions/setup-dotnet@v3.0.3
-        with:
-          dotnet-version: 7.0.100
-      - name: Test the PowerShell module instructions from README.md
-        shell: powershell
-        run: |
-          $module_url = "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Splunk.OTel.DotNet.psm1"
-          $dl_path = Join-Path $env:temp "Splunk.OTel.DotNet.psm1"
-          $log_path = "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\*"
-          Invoke-WebRequest -Uri $module_url -OutFile $dl_path
-          Import-Module $dl_path
-          Install-OpenTelemetryCore
-          $install_dir = Get-OpenTelemetryInstallDirectory
-          Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
-          dotnet help
-          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
-          if (-not (Test-Path $log_path)) { throw "Log file does not exist. Instrumentation test failed." }
-          Remove-Item $log_path
-          Unregister-OpenTelemetryForCurrentSession
-          dotnet help
-          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
-          if (Test-Path $log_path) { throw "Log file exists. Instrumentation unregister failed." }
-          Uninstall-OpenTelemetryCore
-          if (Test-Path $install_dir) { throw "Core files exist. Core uninstall failed." }
-
-  shell-scripts:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - machine: windows-2022
-            log-dir: "/c/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs"
-          - machine: ubuntu-20.04
-            log-dir: "/var/log/opentelemetry/dotnet"
-          - machine: macos-11
-            log-dir: "/var/log/opentelemetry/dotnet"
-    runs-on: ${{ matrix.machine }}
-    steps:
-      - uses: actions/setup-dotnet@v3.0.3
-        with:
-          dotnet-version: 7.0.100
-      - run: brew install coreutils
-        if: ${{ runner.os == 'macOS' }}
-      - name: Create test directory
-        run: sudo mkdir -p ${{ matrix.log-dir }} && sudo chmod a+rwx ${{ matrix.log-dir }}  # workaround before next release
-        if: ${{ runner.os != 'Windows' }}
-      - name: Test the Shell scripts from README.md
-        shell: bash
-        run: |
-          set -e
-          curl -sSfL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/splunk-otel-dotnet-install.sh -O
-          sh ./splunk-otel-dotnet-install.sh
-            test "$(ls -A "$HOME/.splunk-otel-dotnet")"
-          curl -sSfL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/instrument.sh -O
-          . ./instrument.sh
-          dotnet help
-            test "$(ls -A '${{ matrix.log-dir }}' )"
